name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build
        run: |
          cd server
          go mod tidy
          for GOOS in windows linux darwin; do
            for GOARCH in amd64 arm64; do
              output_name=server-$GOOS-$GOARCH
              if [ "${{ os }}" == "windows" ]; then
                output_name=$output_name.exe
              fi
              go build -o ../$output_name server.go
            done
          done
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lenverse-windows-mac-linux
          path: |
            songs/AmazingGrace.txt
            index.html
            songs.html
            lists.html
            verses.html
            main.html
            README.md
            script.js
            stage.html
            style.css
            favicon.png
            server-*
