name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build
        run: |
          cd server
          go mod tidy
          for GOOS in windows linux mac; do
            for GOARCH in amd64 arm64; do
              output_name=server-$GOOS-$GOARCH
              if [ "${{ matrix.os }}" == "windows" ]; then
                output_name=$output_name.exe
              fi
              go build -o ../$output_name server.go
            done
          done
          
      - name: Copy Files
        run: |
          cp -r ./config dist/${{ matrix.os }}-${{ matrix.arch }}/ || true
          cp songs/AmazingGrace.txt index.html songs.html lists.html verses.html main.html README.md script.js stage.html style.css favicon.png dist/${{ matrix.os }}-${{ matrix.arch }}/ || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packaged-binaries
          path: |
            songs/AmazingGrace.txt
            index.html
            songs.html
            lists.html
            verses.html
            main.html
            README.md
            script.js
            stage.html
            style.css
            favicon.png
            lenverse-*
